services:
  - type: web
    name: video-project
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: waitress-serve --port=$PORT video_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: video_project.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: video-db
          property: connectionString

databases:
  - name: video-db
    databaseName: video_db
    user: video_user

